// export const Api = {
//     BASE_URL: 'https://mgenius.in/mobitrailatr/service/',
//     LOGIN: 'Login',
//     EmpSearch: 'EmpSearch',
//     ActionWithoutMeetingTag: 'ActionWithoutMeetingTag',
//     GetMyActions: 'GetMyActions',
//     MyMeetings: 'MyMeetings',
//     AssignedMeetings: 'AssignedMeetings',
//     GetRemarksHistory: 'GetRemarksHistory',
//     SubmitRemark: 'SubmitRemark',
//     CreateMeeting: 'CreateMeeting',
//     GetEmployeesActionsnew: 'GetEmployeesActionsnew',
//     AssignedActionByme: 'AssignedActionByme',
//     AssignedActionByOther: 'AssignedActionByOther',
//     AddactionTab: 'AddactionTab',
//     EditMeeting: 'EditMeeting',
//     EditActionwithmeetingTag: 'EditActionwithmeetingTag',
//     CancelMeeting: 'CancelMeeting',
//     ViewAttendies: 'ViewAttendies',
//     GetEscalationMyTeamDropdown: 'getEscalation_myTeamDropdown',
//     GetEscalationReport: 'getEscalationReport',
//     Group: 'Group',
//     CreateGroup: 'CreateGroup',
//     Groupdelete: 'Groupdelete',
//     EditGroup: 'EditGroup',
//     Fetchproject: 'Fetchproject',
//     CreateProject: 'CreateProject',
//     EditProject: 'EditProject',
//     projectdropdown: 'projectdropdown',
//     GetBadges: 'BadgesDashboard',
//     InsertBadges: 'InsertBadges',
//     SupervisorReport: 'SupervisorReport',
//     Notification: 'Notification',
//     BadgeDisplay: 'BadgeDisplay'



//     // BASE_URL: 'https://mgenius.in/DocMED/',
//     // isDoctorExist: 'DoctorLogin/IsDoctorExists',
//     // verifyOtp: 'DoctorLogin/VerifyOtp',
//     // getDoctorType: 'DoctorLogin/GetMetrics',
//     // registerDoctor: 'DoctorLogin/SignUpDoctor',
//     // scheduleDoctorTme: 'Doctor/ScheduleDoctorTime',
//     // prescribeMedicines: 'Doctor/AddPrescription',
//     // loginDoctor: 'DoctorLogin/DoctorLogin',
//     // loginDoctor_New: 'DoctorLogin/DoctorLogin_new',
//     // verifyOTP_New: 'DoctorLogin/VerifyOtp_new',
//     // getAppointment: 'Doctor/MyAppointment',
//     // isDoctorJoin: 'Doctor/IsDoctorJoin',
//     // isCustomerJoin: 'Customer/IsCustomerJoin',
//     // ExtendAppointment: 'Appointment/ExtendAppointment',
//     // getMedicineList: '/Medicine/GetAllMedicineList',
//     // getStateData: 'Doctor/GetStateMaster',
//     // getCityData: 'Doctor/GetCityMaster',
//     // updateProfile: 'Doctor/UpdateDoctor',
//     // setAgreemnet: 'Doctor/SetAgreementFlag',
//     // getAppointmentSlot: 'Doctor/GetDoctorAppointmentSlot',
//     // scheduleTime: 'Doctor/ScheduleDoctorTime',
//     // UpdateProfilePic: 'Doctor/UpdateDoctorProfilePic',
//     // GetArticlesList: 'Customer/GetArticleList',//add
//     // AddUpdateArticle: 'Doctor/AddUpdateArticle',//add
//     // DeleteArticle: 'doctor/DeleteArticle',
//     // paymentHistory: 'Transaction/GetDoctorTransaction',
//     // getDashboard: 'Dashboard/DoctorDashboard',
//     // getBankData: 'Metrics/GetBankData',
//     // editTime: 'Doctor/UpdateDoctorAppointmentSlot',
//     // cancelAppointment: '/Doctor/CancelAppointmentbyDoctor',
//     // GetPrescriptionHistory: 'Customer/GetPrescriptionHistory',
//     // AddHelpCenter: 'doctor/AddHelpCenter'

// }